build: false
environment:
  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
install:
  - pip install pytest
  - pip install pyyaml
  - pip install pandas
  - pip install pbr
  - pip install vcrpy
  - python setup.py install
test_script:
  - pytest