build: false
environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
install:
  - pip install pytest
  - pip install pyyaml
  - pip install pandas
  - pip install pbr
  - pip install vcrpy
  - python setup.py install
test_script:
  - pytest