version: 2.1

orbs:
  python: circleci/python@1.2
  coveralls: coveralls/coveralls@1.0.6

workflows:
  sample:  # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
    jobs:
      - build-and-test

jobs:
  build-and-test:  # This is the name of the job, feel free to change it to better match what you're trying to do!
    # These next lines defines a Docker executors: https://circleci.com/docs/2.0/executor-types/
    docker:
      - image: cimg/python:3.8
    # Checkout the code as the first step. This is a dedicated CircleCI step.
    # The python orb's install-packages step will install the dependencies from a Pipfile via Pipenv by default.
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: test-requirements.txt
      - run:
          name: Install petpy
          command: python setup.py install
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: pytest
      - coveralls/upload
